services:
  inference-server:
    build:
      context: ./code/scripts
      dockerfile: Dockerfile
    container_name: inference-server
    ports:
      - "8080:8080"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  hf_cache: