services:
  bert-api:
    build:
      context: ./code/src/main/python
      dockerfile: Dockerfile
    container_name: bert-server
    ports:
      - "8080:8080"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  hf_cache: