#File used to set up all the parameters for the project

# ------------------------------------------ PATHS ---------------------------------------------------------------------

language: French

#path to the tokenizerModel
tokenizerModel: src/main/resources/fr/openNLPmodels/fr-token.bin

#path to the sentenceModel
sentenceModel: src/main/resources/fr/openNLPmodels/fr-sent.bin

#path to the posModel
posModel: src/main/resources/fr/openNLPmodels/fr-pos.bin

#path to the lemmatizerModel
lemmatizerModel: src/main/resources/fr/openNLPmodels/fr-lemmatizer.bin

#path to the synonyms file
synonymsFile: src/main/resources/fr/synonyms/synonyms.txt

#path to the language detector model
languageDetectorModel: src/main/resources/langdetect-183.bin

# ------------------------------------------ ANALYZER ------------------------------------------------------------------

#minimum length of a token (minimum number of characters per token)
minLength: 2

#minimum length of a token (minimum number of characters per token)
maxLength: 36

#use the Ngrams filter: select true if you want to use it, false otherwise
nGramsFilter: true

#length of nGram (for words): select the number of shingles
shingleSize: 3

#use the PositionFilter: select true if you want to use it, false otherwise
positionFilter: true

#increment of position to ensure they are consecutive, DO NOT CHANGE (CHECK IF IS IT 1)
positionIncrement: 1

#use the expansionFilter: select true if you want to use it, false otherwise
expansionFilter: true

#use the POSFilter from openNLP: select true if you want to use it, false otherwise
posOpnNLPFilter: true

#use repeatedLetterFilter: select true if you want to use it, false otherwise
repeatedLetterFilter: true

#type of tokenizer to use: select one from [Whitespace, Standard, Letter, Nlp]
tokenizerType: Nlp

#customized stop list
#set the stop list path if it should be used, otherwise leave empty
customStopList: src/main/resources/fr/stoplists/BstoplistFR.txt

#type of stemmer to use for French: select on from [FrenchMinimal, FrenchLight, SnowBall, Nlp, None]
stemFilter: Nlp


