#File used to set up all the parameters for the project

# ------------------------------------------ PATHS ---------------------------------------------------------------------

language: English

#path to the tokenizerModel
tokenizerModel: en/openNLPmodels/en-token.bin

#path to the sentenceModel
sentenceModel: en/openNLPmodels/en-sent.bin

#path to the posModel
posModel: en/openNLPmodels/en-pos.bin

#path to the lemmatizerModel
lemmatizerModel: en/openNLPmodels/en-lemmatizer.bin

#path to the synonyms file
synonymsFile: en/synonyms/synonyms.txt

#path to the language detector model
languageDetectorModel: langdetect-183.bin

# ------------------------------------------ ANALYZER ------------------------------------------------------------------

#minimum length of a token (minimum number of characters per token)
minLength: 2

#minimum length of a token (minimum number of characters per token)
maxLength: 36

#use the Ngrams filter: select true if you want to use it, false otherwise
nGramsFilter: false

#length of nGram (for words): select the number of shingles
shingleSize: 3

#use the PositionFilter: select true if you want to use it, false otherwise
positionFilter: false

#increment of position to ensure they are consecutive, DO NOT CHANGE (CHECK IF IS IT 1)
positionIncrement: 1

#use the expansionFilter: select true if you want to use it, false otherwise
expansionFilter: false

#use the POSFilter from openNLP: select true if you want to use it, false otherwise
posOpnNLPFilter: false

#use repeatedLetterFilter: select true if you want to use it, false otherwise
repeatedLetterFilter: false

#type of tokenizer to use: select one from [Whitespace, Standard, Letter, Nlp]
tokenizerType: Letter

#customized stop list
#set the stop list path if it should be used, otherwise leave empty
customStopList:

#type of stemmer to use for English: select one from [EnglishMinimal, KStem, Porter, SnowBall, Nlp, None]
stemFilter: None
