#File used to set up all the parameters for the project

# ------------------------------------------ PATHS ---------------------------------------------------------------------

language: German

#path to the tokenizerModel
tokenizerModel: de/openNLPmodels/opennlp-de-ud-gsd-tokens-1.3-2.5.4.bin

#path to the sentenceModel
sentenceModel: de/openNLPmodels/opennlp-de-ud-gsd-sentence-1.3-2.5.4.bin

#path to the posModel
posModel: de/openNLPmodels/opennlp-de-ud-gsd-pos-1.3-2.5.4.bin

#path to the lemmatizerModel
lemmatizerModel: de/openNLPmodels/opennlp-de-ud-gsd-lemmas-1.3-2.5.4.bin

#path to the synonyms file
synonymsFile: de/synonims/openthesaurus.txt

#path to the language detector model
languageDetectorModel: langdetect-183.bin

# ------------------------------------------ ANALYZER ------------------------------------------------------------------

#minimum length of a token (minimum number of characters per token)
minLength: 2

#minimum length of a token (minimum number of characters per token)
maxLength: 36

#use the Ngrams filter: select true if you want to use it, false otherwise
nGramsFilter: false

#length of nGram (for words): select the number of shingles
shingleSize: 3

#use the PositionFilter: select true if you want to use it, false otherwise
positionFilter: false

#increment of position to ensure they are consecutive, DO NOT CHANGE (CHECK IF IS IT 1)
positionIncrement: 1

#use the expansionFilter: select true if you want to use it, false otherwise
expansionFilter: true

#use the POSFilter from openNLP: select true if you want to use it, false otherwise
posOpnNLPFilter: true

#use repeatedLetterFilter: select true if you want to use it, false otherwise
repeatedLetterFilter: false

#type of tokenizer to use: select one from [Whitespace, Standard, Letter, Nlp]
tokenizerType: Nlp

#customized stop list
#set the stop list path if it should be used, otherwise leave empty
customStopList: de/stoplists/BstoplistDE.txt

#type of stemmer to use for German: select one from [GermanMinimal, GermanLight, German, SnowBall, Nlp, None]
stemFilter: Nlp
