#!/usr/bin/env python3
"""Run all en_dev test configurations and compare results.

Each run patches config.yml, invokes the searcher JAR, and evaluates with
inline logic. The original config.yml is restored on exit (even on error).

Usage:
    python3 test_en_dev.py
"""

import collections
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = REPO_ROOT / "code/src/main/config/config.yml"
JAR = REPO_ROOT / "code/target/nexa-0.1-jar-with-dependencies.jar"
MAIN_CLASS = "it.unipd.dei.se.nexa.searcher.Searcher"
CLAIMS = REPO_ROOT / "datasets/en_dev.json"
RUNS_DIR = REPO_ROOT / "runs"

TOPICS = "datasets/en_dev.json"

# --------------------------------------------------------------------------- #
# Run matrix
# --------------------------------------------------------------------------- #

RUNS = [
    {
        "id": "nexa-en-dev-baseline",
        "desc": "Baseline (fixed alpha, no PRF)",
        "rerank_alpha": 0.6,
        "rrf_alpha": 0.2,
        "dynamic_alpha": False,
        "prf": False,
    },
    {
        "id": "nexa-en-dev-prf",
        "desc": "PRF enabled",
        "rerank_alpha": 0.6,
        "rrf_alpha": 0.2,
        "dynamic_alpha": False,
        "prf": True,
        "prf_docs": 3,
        "prf_terms": 5,
    },
    {
        "id": "nexa-en-dev-dynamic-alpha",
        "desc": "Dynamic alpha (short=0.8, long=0.2)",
        "rerank_alpha": 0.6,
        "rrf_alpha": 0.2,
        "dynamic_alpha": True,
        "prf": False,
    },
    {
        "id": "nexa-en-dev-interp-03",
        "desc": "Interpolation rerankAlpha=0.3",
        "rerank_alpha": 0.3,
        "rrf_alpha": 0.2,
        "dynamic_alpha": False,
        "prf": False,
    },
    {
        "id": "nexa-en-dev-interp-08",
        "desc": "Interpolation rerankAlpha=0.8",
        "rerank_alpha": 0.8,
        "rrf_alpha": 0.2,
        "dynamic_alpha": False,
        "prf": False,
    },
    {
        "id": "nexa-en-dev-all",
        "desc": "All features (PRF + dynamic alpha + rerankAlpha=0.6)",
        "rerank_alpha": 0.6,
        "rrf_alpha": 0.2,
        "dynamic_alpha": True,
        "prf": True,
        "prf_docs": 3,
        "prf_terms": 5,
    },
]

# --------------------------------------------------------------------------- #
# Config generation
# --------------------------------------------------------------------------- #

CONFIG_TEMPLATE = """\
# auto-generated by test_en_dev.py — do not edit; original is config.yml.bak
collectionPath: datasets/processed/documents/translated/collection_data_en_translated.json
indexPath: "experiment/index"
languageDetectorModel: src/main/resources/langdetect-183.bin
embeddingsEnabled: true
embeddingsServiceUrl: http://localhost:8080/process
translateNonEnglishPublicationsToEnglish: false
translateNonEnglishClaimsToEnglish: false
translationProvider: gemma
translationTargetLanguage: en
translationCommand:
translationServiceUrl: http://127.0.0.1:8081/translate
enableQueryExpansion: false
queryExpansionServiceUrl: http://127.0.0.1:8001/expand
searchMode: hybrid
topics: {topics}
runID: {run_id}
runPath: runs
maxDocsRetrieved: 50
reRank: true
reRankServiceUrl: http://127.0.0.1:8082/rerank
numOfDocsToRerank: 50
rerankAlpha: {rerank_alpha}
rrfAlpha: {rrf_alpha}
rrfK: 60
bm25_k1: 1.2
bm25_b: 0.75
{extra}
"""


def build_config(run: dict) -> str:
    extra_lines = []
    if run["dynamic_alpha"]:
        extra_lines += [
            "rrfAlphaShortQuery: 0.8",
            "rrfAlphaLongQuery: 0.2",
        ]
    if run["prf"]:
        extra_lines += [
            "prf: true",
            f"numOfDocsToRetrieveForPrf: {run.get('prf_docs', 3)}",
            f"numOfTokenFromPrf: {run.get('prf_terms', 5)}",
        ]
    return CONFIG_TEMPLATE.format(
        topics=TOPICS,
        run_id=run["id"],
        rerank_alpha=run["rerank_alpha"],
        rrf_alpha=run["rrf_alpha"],
        extra="\n".join(extra_lines),
    )


# --------------------------------------------------------------------------- #
# Evaluation
# --------------------------------------------------------------------------- #

def evaluate(run_file: Path) -> dict:
    gold = {c["index"]: c["pubkey"] for c in json.loads(CLAIMS.read_text())}
    best: dict[int, int] = {}
    with run_file.open() as f:
        for line in f:
            parts = line.split()
            if len(parts) < 4:
                continue
            qid, pk, rank = int(parts[0]), int(parts[2]), int(parts[3])
            if gold.get(qid) == pk and qid not in best:
                best[qid] = rank

    buckets: collections.Counter = collections.Counter()
    rr_sum = 0.0
    rr5_sum = 0.0
    for qid in gold:
        r = best.get(qid)
        if r is None:
            buckets["missing"] += 1
        else:
            rr_sum += 1.0 / (r + 1)
            if r < 5:
                rr5_sum += 1.0 / (r + 1)
            if r == 0:
                buckets["hit@1"] += 1
            elif r < 5:
                buckets["hit@5"] += 1
            elif r < 10:
                buckets["hit@10"] += 1
            elif r < 100:
                buckets["hit@100"] += 1
            else:
                buckets["hit@1000"] += 1

    n = len(gold)
    return {
        "mrr": rr_sum / n,
        "mrr@5": rr5_sum / n,
        "hit@1": buckets["hit@1"],
        "hit@5": buckets["hit@5"],
        "hit@10": buckets["hit@10"],
        "hit@100": buckets["hit@100"],
        "missing": buckets["missing"],
        "n": n,
    }


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main() -> None:
    if not JAR.exists():
        print(f"ERROR: JAR not found at {JAR}")
        print("Run: cd code && mvn package -DskipTests")
        sys.exit(1)

    backup = CONFIG_PATH.with_suffix(".yml.bak")
    shutil.copy2(CONFIG_PATH, backup)
    print(f"Config backed up to {backup.name}\n")

    results = []
    try:
        for run in RUNS:
            print(f"{'='*60}")
            print(f"Run: {run['id']}")
            print(f"Desc: {run['desc']}")
            print(f"{'='*60}")

            CONFIG_PATH.write_text(build_config(run))

            t0 = time.time()
            proc = subprocess.run(
                ["java", "--add-modules", "jdk.incubator.vector", "-cp", str(JAR), MAIN_CLASS],
                cwd=REPO_ROOT,
                capture_output=False,
            )
            elapsed = time.time() - t0

            if proc.returncode != 0:
                print(f"  FAILED (exit {proc.returncode}), skipping eval")
                results.append({**run, "error": True, "elapsed": elapsed})
                continue

            run_file = RUNS_DIR / f"{run['id']}.txt"
            if not run_file.exists():
                print(f"  Run file not found: {run_file}")
                results.append({**run, "error": True, "elapsed": elapsed})
                continue

            metrics = evaluate(run_file)
            metrics["elapsed"] = elapsed
            results.append({**run, **metrics, "error": False})

            print(f"  MRR@5:   {metrics['mrr@5']:.4f}  (MRR: {metrics['mrr']:.4f})")
            print(f"  hit@1:   {metrics['hit@1']}  hit@5: {metrics['hit@5']}  missing: {metrics['missing']}")
            print(f"  Time:    {elapsed:.1f}s\n")

    finally:
        shutil.copy2(backup, CONFIG_PATH)
        print(f"\nOriginal config.yml restored.")

    # Summary table
    print("\n" + "="*80)
    print(f"{'Run':<34} {'MRR@5':>6} {'MRR':>6} {'hit@1':>6} {'hit@5':>6} {'hit@10':>7} {'miss':>6} {'time':>6}")
    print("-"*80)
    for r in results:
        if r.get("error"):
            print(f"{r['id']:<34}  ERROR")
        else:
            print(
                f"{r['id']:<34} {r['mrr@5']:>6.4f} {r['mrr']:>6.4f} {r['hit@1']:>6} {r['hit@5']:>6}"
                f" {r['hit@10']:>7} {r['missing']:>6} {r['elapsed']:>5.0f}s"
            )
    print("="*80)


if __name__ == "__main__":
    main()
