#!/usr/bin/env python3
"""Run BM25-only baseline across EN/DE/FR dev sets and report MRR@5.

No embeddings, no reranking, no PRF — pure lexical retrieval with the
updated analyzer configs (Standard + Snowball/KStem, no synonyms, no POS filter).

Usage:
    python3 test_lexical_dev.py
"""

import collections
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = REPO_ROOT / "code/src/main/config/config.yml"
JAR = REPO_ROOT / "code/target/nexa-0.1-jar-with-dependencies.jar"
MAIN_CLASS = "it.unipd.dei.se.nexa.searcher.Searcher"
RUNS_DIR = REPO_ROOT / "runs"

LANGS = [
    {
        "lang": "en",
        "topics": "datasets/en_dev.json",
        "claims": REPO_ROOT / "datasets/en_dev.json",
    },
    {
        "lang": "de",
        "topics": "datasets/processed/queries/translated/de_dev_en_translated.json",
        "claims": REPO_ROOT / "datasets/de_dev.json",
    },
    {
        "lang": "fr",
        "topics": "datasets/processed/queries/translated/fr_dev_en_translated.json",
        "claims": REPO_ROOT / "datasets/fr_dev.json",
    },
]

CONFIG_TEMPLATE = """\
# auto-generated by test_lexical_dev.py
collectionPath: datasets/processed/documents/translated/collection_data_en_translated.json
indexPath: "experiment/index"
languageDetectorModel: src/main/resources/langdetect-183.bin
embeddingsEnabled: false
embeddingsServiceUrl: http://localhost:8080/process
translateNonEnglishPublicationsToEnglish: false
translateNonEnglishClaimsToEnglish: false
translationProvider: gemma
translationTargetLanguage: en
translationCommand:
translationServiceUrl: http://127.0.0.1:8081/translate
enableQueryExpansion: false
queryExpansionServiceUrl: http://127.0.0.1:8001/expand
searchMode: lexical
topics: {topics}
runID: {run_id}
runPath: runs
maxDocsRetrieved: 50
reRank: false
reRankServiceUrl: http://127.0.0.1:8082/rerank
numOfDocsToRerank: 50
rerankAlpha: 0.6
rrfAlpha: 0.2
rrfK: 60
bm25_k1: 1.2
bm25_b: 0.75
"""


def evaluate(run_file: Path, claims_file: Path) -> dict:
    gold = {c["index"]: c["pubkey"] for c in json.loads(claims_file.read_text())}
    best: dict[int, int] = {}
    with run_file.open() as f:
        for line in f:
            parts = line.split()
            if len(parts) < 4:
                continue
            qid, pk, rank = int(parts[0]), int(parts[2]), int(parts[3])
            if gold.get(qid) == pk and qid not in best:
                best[qid] = rank

    buckets: collections.Counter = collections.Counter()
    rr_sum = 0.0
    rr5_sum = 0.0
    for qid in gold:
        r = best.get(qid)
        if r is None:
            buckets["missing"] += 1
        else:
            rr_sum += 1.0 / (r + 1)
            if r < 5:
                rr5_sum += 1.0 / (r + 1)
            if r == 0:
                buckets["hit@1"] += 1
            elif r < 5:
                buckets["hit@5"] += 1
            elif r < 10:
                buckets["hit@10"] += 1
            elif r < 100:
                buckets["hit@100"] += 1
            else:
                buckets["hit@1000"] += 1

    n = len(gold)
    return {
        "mrr": rr_sum / n,
        "mrr@5": rr5_sum / n,
        "hit@1": buckets["hit@1"],
        "hit@5": buckets["hit@5"],
        "hit@10": buckets["hit@10"],
        "hit@100": buckets["hit@100"],
        "missing": buckets["missing"],
        "n": n,
    }


def main() -> None:
    if not JAR.exists():
        print(f"ERROR: JAR not found at {JAR}")
        sys.exit(1)

    backup = CONFIG_PATH.with_suffix(".yml.bak")
    shutil.copy2(CONFIG_PATH, backup)
    print("Config backed up.\n")

    results = []
    try:
        for lang_cfg in LANGS:
            run_id = f"nexa-{lang_cfg['lang']}-dev-lexical"
            print(f"{'='*60}")
            print(f"Lang: {lang_cfg['lang'].upper()}  Run: {run_id}")
            print(f"{'='*60}")

            CONFIG_PATH.write_text(CONFIG_TEMPLATE.format(
                topics=lang_cfg["topics"],
                run_id=run_id,
            ))

            t0 = time.time()
            proc = subprocess.run(
                ["java", "--add-modules", "jdk.incubator.vector", "-cp", str(JAR), MAIN_CLASS],
                cwd=REPO_ROOT,
                capture_output=False,
            )
            elapsed = time.time() - t0

            if proc.returncode != 0:
                print(f"  FAILED (exit {proc.returncode})")
                results.append({"lang": lang_cfg["lang"], "run_id": run_id, "error": True, "elapsed": elapsed})
                continue

            run_file = RUNS_DIR / f"{run_id}.txt"
            if not run_file.exists():
                print(f"  Run file not found: {run_file}")
                results.append({"lang": lang_cfg["lang"], "run_id": run_id, "error": True, "elapsed": elapsed})
                continue

            metrics = evaluate(run_file, lang_cfg["claims"])
            metrics["elapsed"] = elapsed
            results.append({"lang": lang_cfg["lang"], "run_id": run_id, "error": False, **metrics})

            print(f"  MRR@5:  {metrics['mrr@5']:.4f}  (MRR: {metrics['mrr']:.4f})")
            print(f"  hit@1:  {metrics['hit@1']}  hit@5: {metrics['hit@5']}  missing: {metrics['missing']}  n: {metrics['n']}")
            print(f"  Time:   {elapsed:.1f}s\n")

    finally:
        shutil.copy2(backup, CONFIG_PATH)
        print("Original config.yml restored.")

    print("\n" + "="*72)
    print(f"{'Run':<32} {'MRR@5':>6} {'MRR':>6} {'hit@1':>6} {'hit@5':>6} {'miss':>6} {'time':>6}")
    print("-"*72)
    for r in results:
        if r.get("error"):
            print(f"{r['run_id']:<32}  ERROR")
        else:
            print(
                f"{r['run_id']:<32} {r['mrr@5']:>6.4f} {r['mrr']:>6.4f}"
                f" {r['hit@1']:>6} {r['hit@5']:>6} {r['missing']:>6} {r['elapsed']:>5.0f}s"
            )
    print("="*72)


if __name__ == "__main__":
    main()
