#!/usr/bin/env python3
"""Pipeline comparison across 9 specific English analyzer configurations.

Tests exactly these pipelines (all without nGrams/synonyms/POS/abbreviation filters):
  1. Standard + LowerCase + Length + NoStop   + NoStem
  2. Standard + LowerCase + Length + StdStop  + NoStem
  3. Standard + LowerCase + Length + StdStop  + EnglishMinimal
  4. Standard + LowerCase + Length + StdStop  + KStem
  5. Standard + LowerCase + Length + StdStop  + Snowball
  6. Standard + LowerCase + Length + StdStop  + Porter
  7. Whitespace + LowerCase + Length + StdStop + EnglishMinimal
  8. Whitespace + LowerCase + Length + StdStop + KStem
  9. Whitespace + LowerCase + Length + StdStop + Snowball

The Searcher queries title_en / abstract_en only, so only the English analyzer
config affects retrieval. Each combo: rebuild index → search EN + FR + DE dev sets.

Usage:
    python3 test_pipeline_dev.py
"""

import collections
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT   = Path(__file__).resolve().parent
CONFIG_MAIN = REPO_ROOT / "code/src/main/config/config.yml"
CONFIG_EN   = REPO_ROOT / "code/src/main/config/config_en.yml"
JAR         = REPO_ROOT / "code/target/nexa-0.1-jar-with-dependencies.jar"
MAIN_CLASS  = "it.unipd.dei.se.nexa.searcher.Searcher"
RUNS_DIR    = REPO_ROOT / "runs"
INDEX_DIR   = REPO_ROOT / "experiment/index"

EN_STOP_PATH = "src/main/resources/en/stoplists/stopListEN_FULL.txt"

# ---------------------------------------------------------------------------
# Pipeline definitions
# ---------------------------------------------------------------------------

PIPELINES = [
    {"id": "std-nostop-nostem",     "tok": "Standard",   "stop": "",            "stem": "None"},
    {"id": "std-stop-nostem",       "tok": "Standard",   "stop": EN_STOP_PATH,  "stem": "None"},
    {"id": "std-stop-enminimal",    "tok": "Standard",   "stop": EN_STOP_PATH,  "stem": "EnglishMinimal"},
    {"id": "std-stop-kstem",        "tok": "Standard",   "stop": EN_STOP_PATH,  "stem": "KStem"},
    {"id": "std-stop-snowball",     "tok": "Standard",   "stop": EN_STOP_PATH,  "stem": "SnowBall"},
    {"id": "std-stop-porter",       "tok": "Standard",   "stop": EN_STOP_PATH,  "stem": "Porter"},
    {"id": "ws-stop-enminimal",     "tok": "Whitespace", "stop": EN_STOP_PATH,  "stem": "EnglishMinimal"},
    {"id": "ws-stop-kstem",         "tok": "Whitespace", "stop": EN_STOP_PATH,  "stem": "KStem"},
    {"id": "ws-stop-snowball",      "tok": "Whitespace", "stop": EN_STOP_PATH,  "stem": "SnowBall"},
]

# ---------------------------------------------------------------------------
# Language test configs
# ---------------------------------------------------------------------------

LANG_TESTS = {
    "en": {
        "topics": "datasets/en_dev.json",
        "claims": REPO_ROOT / "datasets/en_dev.json",
    },
    "fr": {
        "topics": "datasets/processed/queries/translated/fr_dev_en_translated.json",
        "claims": REPO_ROOT / "datasets/fr_dev.json",
    },
    "de": {
        "topics": "datasets/processed/queries/translated/de_dev_en_translated.json",
        "claims": REPO_ROOT / "datasets/de_dev.json",
    },
}

# ---------------------------------------------------------------------------
# Search config template (lexical only)
# ---------------------------------------------------------------------------

SEARCH_TEMPLATE = """\
# auto-generated by test_pipeline_dev.py
collectionPath: datasets/processed/documents/translated/collection_data_en_translated.json
indexPath: "experiment/index"
languageDetectorModel: src/main/resources/langdetect-183.bin
embeddingsEnabled: false
embeddingsServiceUrl: http://localhost:8080/process
translateNonEnglishPublicationsToEnglish: false
translateNonEnglishClaimsToEnglish: false
translationProvider: gemma
translationTargetLanguage: en
translationCommand:
translationServiceUrl: http://127.0.0.1:8081/translate
enableQueryExpansion: false
queryExpansionServiceUrl: http://127.0.0.1:8001/expand
searchMode: lexical
topics: {topics}
runID: {run_id}
runPath: runs
maxDocsRetrieved: 50
reRank: false
reRankServiceUrl: http://127.0.0.1:8082/rerank
numOfDocsToRerank: 50
rerankAlpha: 0.6
rrfAlpha: 0.2
rrfK: 60
bm25_k1: 1.2
bm25_b: 0.75
"""

# ---------------------------------------------------------------------------
# YAML patching
# ---------------------------------------------------------------------------

def patch_yaml(path: Path, patches: dict) -> str:
    content = path.read_text()
    original = content
    for key, value in patches.items():
        content, n = re.subn(
            rf'^({re.escape(key)}:)[ \t]*.*$',
            rf'\1 {value}',
            content,
            flags=re.MULTILINE,
        )
        if n == 0:
            print(f"  [WARN] key '{key}' not found in {path.name}")
    path.write_text(content)
    return original

# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate(run_file: Path, claims_file: Path) -> dict:
    gold = {c["index"]: c["pubkey"] for c in json.loads(claims_file.read_text())}
    best: dict[int, int] = {}
    with run_file.open() as f:
        for line in f:
            parts = line.split()
            if len(parts) < 4:
                continue
            qid, pk, rank = int(parts[0]), int(parts[2]), int(parts[3])
            if gold.get(qid) == pk and qid not in best:
                best[qid] = rank

    buckets: collections.Counter = collections.Counter()
    rr_sum  = 0.0
    rr5_sum = 0.0
    for qid in gold:
        r = best.get(qid)
        if r is None:
            buckets["missing"] += 1
        else:
            rr_sum  += 1.0 / (r + 1)
            if r < 5:
                rr5_sum += 1.0 / (r + 1)
            if r == 0:      buckets["hit@1"]   += 1
            elif r < 5:     buckets["hit@5"]   += 1
            elif r < 10:    buckets["hit@10"]  += 1
            elif r < 100:   buckets["hit@100"] += 1
    n = len(gold)
    return {
        "mrr":     rr_sum  / n,
        "mrr@5":   rr5_sum / n,
        "hit@1":   buckets["hit@1"],
        "hit@5":   buckets["hit@5"],
        "hit@10":  buckets["hit@10"],
        "missing": buckets["missing"],
        "n":       n,
    }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def rebuild_index() -> float:
    shutil.rmtree(INDEX_DIR, ignore_errors=True)
    t0 = time.time()
    proc = subprocess.run(
        ["java", "--add-modules", "jdk.incubator.vector",
         "-cp", str(JAR), "it.unipd.dei.se.nexa.indexer.DirectoryIndexer"],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    elapsed = time.time() - t0
    if proc.returncode != 0:
        print("  [INDEX FAILED]")
        print(proc.stderr[-1000:])
        return -1.0
    last = [l for l in proc.stdout.splitlines() if l.strip()]
    if last:
        print(f"  {last[-1].strip()}  ({elapsed:.0f}s)")
    return elapsed


def run_search(lang: str, run_id: str) -> dict | None:
    lt = LANG_TESTS[lang]
    CONFIG_MAIN.write_text(SEARCH_TEMPLATE.format(
        topics=lt["topics"], run_id=run_id,
    ))
    proc = subprocess.run(
        ["java", "--add-modules", "jdk.incubator.vector",
         "-cp", str(JAR), MAIN_CLASS],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    run_file = RUNS_DIR / f"{run_id}.txt"
    if proc.returncode != 0 or not run_file.exists():
        print(f"  [{lang.upper()} FAILED]")
        return None
    return evaluate(run_file, lt["claims"])

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not JAR.exists():
        print("ERROR: JAR not found. Run: cd code && mvn package -DskipTests")
        sys.exit(1)

    RUNS_DIR.mkdir(exist_ok=True)

    backup_main = CONFIG_MAIN.read_text()
    backup_en   = CONFIG_EN.read_text()

    langs = list(LANG_TESTS.keys())
    print(f"Pipeline sweep: {len(PIPELINES)} configs × {len(langs)} languages\n")

    # results[pipeline_id][lang] = metrics dict
    results: dict[str, dict] = {p["id"]: {} for p in PIPELINES}

    try:
        for i, pipe in enumerate(PIPELINES, 1):
            pid = pipe["id"]
            print(f"[{i}/{len(PIPELINES)}] {pid}")
            print(f"  Tokenizer={pipe['tok']}  Stop={'on' if pipe['stop'] else 'off'}  Stem={pipe['stem']}")

            # Patch config_en.yml — disable everything not in this pipeline
            patch_yaml(CONFIG_EN, {
                "tokenizerType":       pipe["tok"],
                "stemFilter":          pipe["stem"],
                "customStopList":      pipe["stop"],
                "synonymsFile":        "",
                "nGramsFilter":        "false",
                "positionFilter":      "false",
                "expansionFilter":     "false",
                "repeatedLetterFilter":"false",
                "posOpnNLPFilter":     "false",
            })

            idx_time = rebuild_index()
            if idx_time < 0:
                continue

            for lang in langs:
                run_id  = f"pl-{pid}-{lang}"
                metrics = run_search(lang, run_id)
                if metrics:
                    results[pid][lang] = metrics
                    print(f"  {lang.upper()}: MRR@5={metrics['mrr@5']:.4f}  "
                          f"hit@1={metrics['hit@1']}  miss={metrics['missing']}")
            print()

    finally:
        CONFIG_EN.write_text(backup_en)
        CONFIG_MAIN.write_text(backup_main)
        print("Configs restored.\n")

    # ---------------------------------------------------------------------------
    # Per-language tables sorted by MRR@5
    # ---------------------------------------------------------------------------
    col = 24
    hdr = f"{'pipeline':<{col}} {'MRR@5':>6} {'MRR':>6} {'hit@1':>6} {'hit@5':>6} {'hit@10':>7} {'miss':>5}"
    sep = "-" * len(hdr)

    for lang in langs:
        rows = [(pid, results[pid][lang]) for pid in results if lang in results[pid]]
        rows.sort(key=lambda x: x[1]["mrr@5"], reverse=True)

        print(f"\n{'='*len(hdr)}")
        print(f"  {lang.upper()} dev — sorted by MRR@5")
        print(f"{'='*len(hdr)}")
        print(hdr)
        print(sep)
        for pid, m in rows:
            print(f"{pid:<{col}} {m['mrr@5']:>6.4f} {m['mrr']:>6.4f}"
                  f" {m['hit@1']:>6} {m['hit@5']:>6} {m['hit@10']:>7} {m['missing']:>5}")
        if rows:
            print(sep)
            print(f"  best : {rows[0][0]}  MRR@5={rows[0][1]['mrr@5']:.4f}")
            print(f"  worst: {rows[-1][0]}  MRR@5={rows[-1][1]['mrr@5']:.4f}")

    # ---------------------------------------------------------------------------
    # Cross-language average table
    # ---------------------------------------------------------------------------
    print(f"\n{'='*72}")
    print("  Cross-language avg MRR@5")
    print(f"{'='*72}")
    hdr2 = f"{'pipeline':<{col}} {'avg':>6}  " + "  ".join(f"{l.upper():>6}" for l in langs)
    print(hdr2)
    print("-" * 72)

    rows2 = []
    for pid in results:
        scores = [results[pid][l]["mrr@5"] for l in langs if l in results[pid]]
        if scores:
            rows2.append((pid, sum(scores) / len(scores), scores))
    rows2.sort(key=lambda x: x[1], reverse=True)

    for pid, avg, scores in rows2:
        per = {l: results[pid].get(l, {}).get("mrr@5", float("nan")) for l in langs}
        per_str = "  ".join(f"{per[l]:>6.4f}" for l in langs)
        print(f"{pid:<{col}} {avg:>6.4f}  {per_str}")

    if rows2:
        print(f"\n  best overall: {rows2[0][0]}  avg={rows2[0][1]:.4f}")


if __name__ == "__main__":
    main()
