#!/usr/bin/env python3
"""Test nGrams (ShingleFilter) on/off on top of the best pipeline:
   Standard + LowerCase + EnglishPossessive + Length + StopList + [Shingles] + KStem

Pipelines tested:
  std-stop-kstem           nGrams=off  (reference)
  std-stop-kstem-ng2       nGrams=on   shingleSize=2
  std-stop-kstem-ng3       nGrams=on   shingleSize=3

Usage:
    python3 test_ngrams_dev.py
"""

import collections
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT   = Path(__file__).resolve().parent
CONFIG_MAIN = REPO_ROOT / "code/src/main/config/config.yml"
CONFIG_EN   = REPO_ROOT / "code/src/main/config/config_en.yml"
JAR         = REPO_ROOT / "code/target/nexa-0.1-jar-with-dependencies.jar"
MAIN_CLASS  = "it.unipd.dei.se.nexa.searcher.Searcher"
RUNS_DIR    = REPO_ROOT / "runs"
INDEX_DIR   = REPO_ROOT / "experiment/index"

EN_STOP_PATH = "src/main/resources/en/stoplists/stopListEN_FULL.txt"

PIPELINES = [
    {"id": "std-stop-kstem",     "ngrams": False, "shingle": 3},
    {"id": "std-stop-kstem-ng2", "ngrams": True,  "shingle": 2},
    {"id": "std-stop-kstem-ng3", "ngrams": True,  "shingle": 3},
]

LANG_TESTS = {
    "en": {
        "topics": "datasets/en_dev.json",
        "claims": REPO_ROOT / "datasets/en_dev.json",
    },
    "fr": {
        "topics": "datasets/processed/queries/translated/fr_dev_en_translated.json",
        "claims": REPO_ROOT / "datasets/fr_dev.json",
    },
    "de": {
        "topics": "datasets/processed/queries/translated/de_dev_en_translated.json",
        "claims": REPO_ROOT / "datasets/de_dev.json",
    },
}

SEARCH_TEMPLATE = """\
# auto-generated by test_ngrams_dev.py
collectionPath: datasets/processed/documents/translated/collection_data_en_translated.json
indexPath: "experiment/index"
languageDetectorModel: src/main/resources/langdetect-183.bin
embeddingsEnabled: false
embeddingsServiceUrl: http://localhost:8080/process
translateNonEnglishPublicationsToEnglish: false
translateNonEnglishClaimsToEnglish: false
translationProvider: gemma
translationTargetLanguage: en
translationCommand:
translationServiceUrl: http://127.0.0.1:8081/translate
enableQueryExpansion: false
queryExpansionServiceUrl: http://127.0.0.1:8001/expand
searchMode: lexical
topics: {topics}
runID: {run_id}
runPath: runs
maxDocsRetrieved: 50
reRank: false
reRankServiceUrl: http://127.0.0.1:8082/rerank
numOfDocsToRerank: 50
rerankAlpha: 0.6
rrfAlpha: 0.2
rrfK: 60
bm25_k1: 1.2
bm25_b: 0.75
"""


def patch_yaml(path, patches):
    content = path.read_text()
    original = content
    for key, value in patches.items():
        content, n = re.subn(
            rf'^({re.escape(key)}:)[ \t]*.*$',
            rf'\1 {value}',
            content, flags=re.MULTILINE,
        )
        if n == 0:
            print(f"  [WARN] '{key}' not found in {path.name}")
    path.write_text(content)
    return original


def evaluate(run_file, claims_file):
    gold = {c["index"]: c["pubkey"] for c in json.loads(claims_file.read_text())}
    best = {}
    with run_file.open() as f:
        for line in f:
            parts = line.split()
            if len(parts) < 4:
                continue
            qid, pk, rank = int(parts[0]), int(parts[2]), int(parts[3])
            if gold.get(qid) == pk and qid not in best:
                best[qid] = rank

    buckets = collections.Counter()
    rr_sum = rr5_sum = 0.0
    for qid in gold:
        r = best.get(qid)
        if r is None:
            buckets["missing"] += 1
        else:
            rr_sum += 1.0 / (r + 1)
            if r < 5:
                rr5_sum += 1.0 / (r + 1)
            if r == 0:     buckets["hit@1"] += 1
            elif r < 5:    buckets["hit@5"] += 1
            elif r < 10:   buckets["hit@10"] += 1
            elif r < 100:  buckets["hit@100"] += 1
    n = len(gold)
    return {"mrr": rr_sum/n, "mrr@5": rr5_sum/n,
            "hit@1": buckets["hit@1"], "hit@5": buckets["hit@5"],
            "hit@10": buckets["hit@10"], "missing": buckets["missing"], "n": n}


def rebuild_index():
    shutil.rmtree(INDEX_DIR, ignore_errors=True)
    t0 = time.time()
    proc = subprocess.run(
        ["java", "--add-modules", "jdk.incubator.vector",
         "-cp", str(JAR), "it.unipd.dei.se.nexa.indexer.DirectoryIndexer"],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    elapsed = time.time() - t0
    if proc.returncode != 0:
        print("  [INDEX FAILED]"); print(proc.stderr[-500:])
        return -1.0
    last = [l for l in proc.stdout.splitlines() if l.strip()]
    if last:
        print(f"  {last[-1].strip()}  ({elapsed:.0f}s)")
    return elapsed


def run_search(lang, run_id):
    lt = LANG_TESTS[lang]
    CONFIG_MAIN.write_text(SEARCH_TEMPLATE.format(topics=lt["topics"], run_id=run_id))
    proc = subprocess.run(
        ["java", "--add-modules", "jdk.incubator.vector", "-cp", str(JAR), MAIN_CLASS],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    run_file = RUNS_DIR / f"{run_id}.txt"
    if proc.returncode != 0 or not run_file.exists():
        print(f"  [{lang.upper()} FAILED]"); return None
    return evaluate(run_file, lt["claims"])


def main():
    if not JAR.exists():
        print("ERROR: JAR not found."); sys.exit(1)

    RUNS_DIR.mkdir(exist_ok=True)
    backup_main = CONFIG_MAIN.read_text()
    backup_en   = CONFIG_EN.read_text()

    langs = list(LANG_TESTS.keys())
    results = {}

    try:
        for i, pipe in enumerate(PIPELINES, 1):
            pid = pipe["id"]
            ng  = pipe["ngrams"]
            print(f"[{i}/{len(PIPELINES)}] {pid}  nGrams={'on (shingle=' + str(pipe['shingle']) + ')' if ng else 'off'}")

            patch_yaml(CONFIG_EN, {
                "tokenizerType":        "Standard",
                "stemFilter":           "KStem",
                "customStopList":       EN_STOP_PATH,
                "synonymsFile":         "",
                "nGramsFilter":         str(ng).lower(),
                "shingleSize":          str(pipe["shingle"]),
                "positionFilter":       str(ng).lower(),
                "expansionFilter":      "false",
                "repeatedLetterFilter": "false",
                "posOpnNLPFilter":      "false",
            })

            if rebuild_index() < 0:
                continue

            results[pid] = {}
            for lang in langs:
                m = run_search(lang, f"ng-{pid}-{lang}")
                if m:
                    results[pid][lang] = m
                    print(f"  {lang.upper()}: MRR@5={m['mrr@5']:.4f}  "
                          f"hit@1={m['hit@1']}  hit@5={m['hit@5']}  miss={m['missing']}")
            print()

    finally:
        CONFIG_EN.write_text(backup_en)
        CONFIG_MAIN.write_text(backup_main)
        print("Configs restored.\n")

    # Summary table
    col = 24
    hdr = f"{'pipeline':<{col}} {'MRR@5':>6} {'MRR':>6} {'hit@1':>6} {'hit@5':>6} {'hit@10':>7} {'miss':>5}"
    sep = "-" * len(hdr)

    for lang in langs:
        rows = [(pid, results[pid][lang]) for pid in results if lang in results[pid]]
        rows.sort(key=lambda x: x[1]["mrr@5"], reverse=True)
        print(f"\n{'='*len(hdr)}")
        print(f"  {lang.upper()} dev")
        print(f"{'='*len(hdr)}")
        print(hdr); print(sep)
        for pid, m in rows:
            print(f"{pid:<{col}} {m['mrr@5']:>6.4f} {m['mrr']:>6.4f}"
                  f" {m['hit@1']:>6} {m['hit@5']:>6} {m['hit@10']:>7} {m['missing']:>5}")

    print(f"\n{'='*72}")
    print("  Cross-language avg MRR@5")
    print(f"{'='*72}")
    hdr2 = f"{'pipeline':<{col}} {'avg':>6}  " + "  ".join(f"{l.upper():>6}" for l in langs)
    print(hdr2); print("-"*72)
    rows2 = []
    for pid in results:
        scores = [results[pid][l]["mrr@5"] for l in langs if l in results[pid]]
        if scores:
            rows2.append((pid, sum(scores)/len(scores)))
    rows2.sort(key=lambda x: x[1], reverse=True)
    for pid, avg in rows2:
        per = "  ".join(f"{results[pid].get(l,{}).get('mrr@5', float('nan')):>6.4f}" for l in langs)
        print(f"{pid:<{col}} {avg:>6.4f}  {per}")
    if rows2:
        print(f"\n  best overall: {rows2[0][0]}  avg={rows2[0][1]:.4f}")


if __name__ == "__main__":
    main()
