package it.unipd.dei.se.nexa.searcher;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.TokenStream;
import org.apache.lucene.analysis.synonym.SynonymMap;
import org.apache.lucene.analysis.tokenattributes.CharTermAttribute;
import org.apache.lucene.util.CharsRef;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import it.unipd.dei.se.nexa.analyzer.EnglishAnalyzer;
import it.unipd.dei.se.nexa.utility.ConfigManager;

public class SearcherUtil {

    private static final ConfigManager config = ConfigManager.getGlobalConfig();
    private static final String PUNC = "\\p{Punct}";

    private SearcherUtil() {
    }


    public static List<String> queryAnalyzer(Analyzer analyzer, String query) throws IOException {
        List<String> results = new ArrayList<>();

        try (TokenStream stream = analyzer.tokenStream("field", new StringReader(query))) {
            stream.reset();
            final CharTermAttribute tokenTerm = stream.addAttribute(CharTermAttribute.class);

            while (stream.incrementToken())
                results.add(tokenTerm.toString());
            stream.end();
        }
        return results;
    }



    public static Map<String, String[]> readSynonyms(String synonymMapFile) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(synonymMapFile))) {
            String line;
            Map<String, String[]> m = new HashMap<>();
            while ((line = reader.readLine()) != null) {
                String[] word = line.split("=>");
                if (word.length > 1) {
                    if (!word[1].contains(",")) {
                        String[] synonym = {word[1]};
                        m.put(word[0], synonym);
                    } else
                        m.put(word[0], word[1].split(","));
                }
            }
            return m;
        }
    }


    /**
     * Sends a POST request to a custom HuggingFace endpoint using the provided prompt,
     * and retrieves related terms generated by a Large Language Model (LLM).
     */
    private static final Map<String, String[]> LLM_CACHE = new HashMap<>();

    public static String[] getRelatedTermsFromLLM(String query, String apiKey) throws IOException {
        String[] cached = LLM_CACHE.get(query);
        if (cached != null) {
            return cached;
        }

        HttpURLConnection con = null;
        for (int attempt = 0; attempt < 5; attempt++) {
            URL url = URI.create(config.getString("llmServiceUrl")).toURL();
            con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Authorization", "Bearer ".concat(apiKey));
            con.setRequestProperty("Content-Type", "application/json");
            con.setConnectTimeout(10000);
            con.setReadTimeout(30000);

            String jsonInputString = getBody(query);
            con.setDoOutput(true);
            try (OutputStream os = con.getOutputStream()) {
                byte[] input = jsonInputString.getBytes(StandardCharsets.UTF_8);
                os.write(input, 0, input.length);
            }

            int code = con.getResponseCode();
            if (code == HttpURLConnection.HTTP_OK) {
                break;
            }
            if (code == 429) {
                String retryAfter = con.getHeaderField("Retry-After");
                long sleepMs = 2000L;
                if (retryAfter != null) {
                    try {
                        sleepMs = (long) (Double.parseDouble(retryAfter) * 1000);
                    } catch (NumberFormatException ignored) {}
                }
                sleepMs = Math.min(sleepMs, 30_000L) + 250L * attempt;
                try {
                    Thread.sleep(sleepMs);
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                    return new String[]{""};
                }
                con.disconnect();
                continue;
            }
            System.err.println("Error: " + code + " " + con.getResponseMessage());
            return new String[]{""};
        }
        if (con == null || con.getResponseCode() != HttpURLConnection.HTTP_OK) {
            System.err.println("LLM expansion: gave up after retries");
            return new String[]{""};
        }

        // Read API response
        try (BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8))) {
            StringBuilder responseBuilder = new StringBuilder();
            String line;
            while ((line = br.readLine()) != null)
                responseBuilder.append(line);

            ObjectMapper mapper = new ObjectMapper();
            JsonNode root = mapper.readTree(responseBuilder.toString());

            String content = root.path("choices")
                    .get(0)
                    .path("message")
                    .path("content")
                    .asText();

            String[] newTerms = Arrays.stream(content.split(","))
                    .map(token -> token.replaceAll("[\\n\\t\\r\"']", "").trim())
                    .filter(token -> !token.isEmpty())
                    .toArray(String[]::new);

            Integer expectedTokens = config.getInt("numOfTokenFromLLM");
            if (expectedTokens != null && newTerms.length != expectedTokens)
                System.err.println("The terms returned by the LLM are different from the requested ones");

            try (EnglishAnalyzer analyzer = new EnglishAnalyzer()) {
                String[] result = queryAnalyzer(analyzer, String.join(" ", newTerms)).toArray(new String[0]);
                LLM_CACHE.put(query, result);
                return result;
            }
        }
    }

    private static String getBody(String query) {
        String llmModel = config.getString("llmModel");
        if (llmModel == null || llmModel.isBlank()) {
            llmModel = (config.getString("llmServiceUrl") != null && config.getString("llmServiceUrl").contains("api.openai.com"))
                    ? "gpt-3.5-turbo" : "deepseek/deepseek-v3-0324";
        }

        ObjectMapper mapper = new ObjectMapper();
        try {
            Map<String, Object> body = new HashMap<>();
            body.put("model", llmModel);
            Map<String, String> message = new HashMap<>();
            message.put("role", "user");
            message.put("content", String.format(
                    "Write ONLY %d related words about this topic: %s, separated by commas. No sentences or punctuation.",
                    config.getInt("numOfTokenFromLLM"), query));
            body.put("messages", List.of(message));
            body.put("max_tokens", 50);
            body.put("temperature", 0.5);
            body.put("top_p", 0.9);
            return mapper.writeValueAsString(body);
        } catch (IOException e) {
            throw new RuntimeException("Failed to build LLM request body", e);
        }
    }

    public static String[] getRelatedTermsWord2Vec(List<String> query) throws IOException {
        List<String> allRelatedTerms = new ArrayList<>();
        ObjectMapper mapper = new ObjectMapper();

        for (String token : query) {
            URL url = URI.create("http://localhost:8081/similar?word=" + URLEncoder.encode(token, StandardCharsets.UTF_8)).toURL();
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");
            con.setRequestProperty("Accept", "application/json");
            con.setConnectTimeout(10000);
            con.setReadTimeout(10000);

            if (con.getResponseCode() == 200) {
                try (BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()))) {
                    String[] relatedTerms = mapper.readValue(br, String[].class);
                    allRelatedTerms.addAll(Arrays.asList(relatedTerms));
                } finally {
                    con.disconnect();
                }
            } else
                return new String[]{""};
        }
        try (EnglishAnalyzer analyzer = new EnglishAnalyzer()) {
            return queryAnalyzer(analyzer, String.join(" ", allRelatedTerms)).toArray(new String[0]);
        }
    }

    public static void main(String[] args) {
        try {
            System.out.println(" Query Expansion with LLM...");

            String apiKey = config.getString("openApiKey");
            if (apiKey == null || apiKey.isBlank() || apiKey.contains("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")) {
                System.err.println("ERROR: invalid API KEY in config.yml (openApiKey)!");
                return;
            }

            String testQuery = "climate change global warming";
            System.out.println("Query original: " + testQuery);
            System.out.println("Interrogation...");

            String[] expandedTerms = getRelatedTermsFromLLM(testQuery, apiKey);

            System.out.println("\n✅ Test complete!");
            System.out.println("Words extract (" + expandedTerms.length + "):");
            for (String term : expandedTerms) {
                System.out.println(" - " + term);
            }

        } catch (Exception e) {
            System.err.println("❌ Error:");
            e.printStackTrace();
        }
    }
}
